### ISSUE TITLE
Mail configuratie

### ISSUE THREAD

**Issue by robstek** [IDgis/download-tool#57]
connectie met mail smtp server

credentials in docker-compose.override.yml:

```
version: "2"

services:
  feedback_ok:
    environment:
      - SMTP_USER="noreply@geoportaaloverijssel.nl"
      - SMTP_PASSWORD="..."
  feedback_error:
    environment:
      - SMTP_USER="noreply@geoportaaloverijssel.nl"
      - SMTP_PASSWORD="..."
```
